### ISSUE TITLE
[Question] 무기로 공격하는 방법

### ISSUE THREAD

**Issue by pengzer1** [Team-Aster/Aster-GameDev#15]
무기로 공격하는 방법을 크게 3가지로 선택할 수 있을 것 같습니다.

1. 마우스 클릭으로 Animation 동작과 함께 무기가 휘둘러짐
2. 마우스 움직임으로 무기를 든 팔을 움직이면서 무기가 휘둘러짐
3. 마우스 클릭 후 드래그로 일정 범위만큼 팔을 움직이면서 무기가 휘둘러짐

1번의 경우, 일반적인 게임에서 가장 기본적으로 공격하는 방식이라고 생각하면 될 것 같습니다.(ex) fps 게임에서 근거리 무기 공격하는 방식)
2번의 경우, 캐릭터와 카메라를 동기화 시킨 후, 캐릭터 회전을 마우스로 하면서 팔을 휘두르는 방식과 마우스로 팔만 움직이는 방식으로 나뉠 수 있겠습니다.

1번은 Animation이 활성화 되었을 때, 무기 collider가 활성화 되면서 충돌을 인식하는 방식
2번은 계속 무기 collider가 활성화 돼있는 방식으로 구현될 것 같습니다.
3번의 경우는 두 방식 모두 채택할 수 있을 것 같습니다.

**Comment by HUSK-321** [comment]
> 2. 마우스 움직임으로 무기를 든 팔을 움직이면서 무기가 휘둘러짐

이 부분의 기획이 좋아 보입니다.
일단 다른 기획들에 대한 코멘트를 생각해보면

- 1 번의 경우에는 움직임이 Animation 을 타겟팅 하는 것이다 보니 너무 단순해지는 경우가 있는 것 같습니다. 유저에게 선택권이 없는 느낌이죠.
- 3 번의 경우에는 사용자가 계속해서 마우스 클릭을 해야 한다는 번거로움이 있을 것 같습니다. 모바일과 PC 환경에서 일체화는 될 수 있겠지만 PC 유저들이 굳이 클릭을 계속 쥐고 있을 이유는 없을 것 같습니다.

때문에 2번이 가장 좋은 선택지로 보입니다.

--- 

추가적인 의견이 있다면 일단 플랫폼이 2가지로 나뉜다는 점입니다.
- PC
- Android
크게 보면 모바일과 PC 인데 이 두가지 경우를 전부 고려해서 제작되었으면 합니다. IPayerWeaponController 같은 인터페이스를 하나 장만하고 이 인터페이스를 상속받는 PCWeaponController, MobileWeaponController 2개를 만들고 빌드시 서로 교체하면서 만들면 좋을 것 같습니다.

자세한 부분은 `전략 패턴`에 있을 것으로 보입니다.

**Comment by pengzer1** [comment]
알겠습니다. 2번 방식(캐릭터 회전을 마우스로 하는 방식)으로 하는 걸로 결정하겠습니다.
